spring:
  application:
    name: convert-currency
    
server:
  port: 8102

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    
  client:
    service-url:
      defaultZone : http://localhost:8100/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
      